name: RemoteVizualizer

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install requirements
        run: pip install -r requirements.txt
        working-directory: ./remote-vizualizer
      - name: pylint
        run: pylint remote-vizualizer --rcfile=.pylintrc
